# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-1.0.3
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2019-08-24T02:15:14Z
  labels:
    app: camelsap
  name: camelsap
spec:
  volumes:
    - name: camelsap
      persistentVolumeClaim:
       claimName: sapdata
  containers:
  - command:
    - /bin/sh
    - -c
    - java -Djava.library.path=/home/marc/sap -jar camelsapdemo-0.0.1-SNAPSHOT.jar
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: oci
    image: quay.io/marcf5/camelsap
    name: camelsap
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    workingDir: /home/marc/sap
  imagePullSecrets:
    - name: staging-secret
status: {}
